version: "3.8"

services:
  api:
    build: ./api
    container_name: fastapi
    networks:
      - tor_net
    expose:
      - 8000

  tor:
    image: osminogin/tor-simple
    container_name: tor
    volumes:
      - ./torrc:/etc/tor/torrc
      - ./hidden_service:/var/lib/tor/hidden_service
    command: >
      sh -c "
      mkdir -p /var/lib/tor/hidden_service &&
      chmod 700 /var/lib/tor/hidden_service &&
      chown -R tor:tor /var/lib/tor &&
      exec tor -f /etc/tor/torrc
      "
    depends_on:
      - api
    networks:
      - tor_net

networks:
  tor_net:

volumes:
  tor_hidden_service: